openapi: 3.0.3
info:
  title: Ecommerce - Order / Category Microservice API
  description: >
    API do microserviço de Orders/Categories. O `customerId` é obtido do token JWT
    (bearer). Este arquivo é um template baseado no código enviado e deve ser ajustado conforme necessário.
  version: "1.0.0"
servers:
  - url: http://localhost:8080
    description: Servidor LOCAL (ajuste conforme ambiente)
components:
 
  responses:
    BadRequestSimpleMessage:
      description: Erro de validação ou de negócio (HTTP 400)
      content:
        application/json:
          schema:
            type: object
            oneOf:
              - properties:
                  message:
                    type: string
                    example: "O tipo de pagamento é obrigatório"
              - properties:
                  errors:
                    type: object
                    description: Lista de erros de validação, onde cada campo possui sua mensagem.
                    additionalProperties:
                      type: string
                    example:
                      customerId: "O ID do cliente é obrigatório"
                      paymentType: "O tipo de pagamento é obrigatório"

    InternalServerErrorSimple:
      description: Erro interno no servidor (HTTP 500)
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Erro interno no servidor"

  schemas:
    # Enums
    OrderStatus:
      type: string
      enum: [PENDING,DELIVERED,CANCELED]

    PaymentType:
      type: string
      enum: [BILL, CREDIT_CARD,DEBIT_CARD, PIX]

    # Product DTOs
    ProductCreateDTO:
      type: object
      properties:
        itemName:
          type: string
          example: "Camiseta gola polo"
        unitPrice:
          type: number
          format: double
          example: 79.9
          minimum: 0.01
          exclusiveMinimum: true
        quantity:
          type: integer
          example: 10
          minimum: 1
        categoryId:
          type: string
          format: uuid
          example: "a3763ba2-6761-4441-be88-e287db70f46e"
        barcode:
          type: string
          example: "0123456789012"
      required:
        - itemName
        - unitPrice
        - - quantity
        - categoryId

    ProductResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        itemName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
          format: double
        barcode:
          type: string
        category:
          $ref: "#/components/schemas/CategoryProductResponseDTO"

    # Category DTOs
    CategoryProductCreateDTO:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    CategoryProductResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
       
    OrderItemResponseDTO:
      type: object
      properties:
        itemName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
          format: double
        barcode:
          type: string
        categoryId:
          type: string
          format: uuid

    OrderCreateDTO:
      type: object
      description: DTO usado pelo cliente para criar um pedido. O customerId é obtido do JWT.
      properties:
        customerId:
          type: string
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponseDTO'
        
      required:
        - items
        - paymentType


    OrderResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        customerId:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponseDTO'
        totalAmount:
          type: number
          format: double
        status:
          $ref: '#/components/schemas/OrderStatus'
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        createdAt:
          type: string
          format: date-time

  parameters:
    orderIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid

paths:
  /order:
    post:
      summary: Criar um novo pedido
      description: Cria um novo pedido. O `customerId` é extraído do token JWT (bearer). Retorna 201 Created com o OrderResponseDTO.
      security:
        - bearerAuth: []
      requestBody:
        description: Dados do pedido
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateDTO'
      
      responses:
        '201':
          description: Pedido criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDTO'
        '400':
          $ref: '#/components/responses/BadRequestSimpleMessage'
        '500':
          $ref: '#/components/responses/InternalServerErrorSimple'

  /category:
    post:
      summary: Criar categoria
      description: Cria uma categoria de produto.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryProductCreateDTO'
      responses:
        '201':
          description: Categoria criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryProductResponseDTO'
        
 
security:
  - bearerAuth: []
